from datetime import date
from typing import Protocol
from uuid import UUID

from vrf.domain.entities import (
    Cliente,
    Comprobante,
    Empresa,
    Especialidad,
    Obra,
    Proveedor,
    RefreshToken,
    Rubro,
    TipoPago,
    Usuario,
)


class UnitOfWork(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class EspecialidadRepository(Protocol):
    def get(self, id: UUID) -> Especialidad | None: ...
    def list_by_grupo(self, grupo_id: UUID) -> list[Especialidad]: ...
    def add(self, item: Especialidad) -> None: ...
    def save(self, item: Especialidad) -> None: ...
    def get_by_slug(self, grupo_id: UUID, slug: str) -> Especialidad | None: ...


class EmpresaRepository(Protocol):
    def get(self, id: UUID) -> Empresa | None: ...
    def list_by_grupo(self, grupo_id: UUID) -> list[Empresa]: ...
    def get_by_cuit(self, cuit: str) -> Empresa | None: ...
    def add(self, item: Empresa) -> None: ...
    def save(self, item: Empresa) -> None: ...
    def list_by_ids(self, ids: list[UUID]) -> list[Empresa]: ...


class ClienteRepository(Protocol):
    def get(self, id: UUID) -> Cliente | None: ...
    def list_by_grupo(self, grupo_id: UUID) -> list[Cliente]: ...
    def get_by_nombre(self, grupo_id: UUID, nombre: str) -> Cliente | None: ...
    def add(self, item: Cliente) -> None: ...
    def save(self, item: Cliente) -> None: ...


class ObraRepository(Protocol):
    def get(self, id: UUID) -> Obra | None: ...
    def list_by_cliente(self, cliente_id: UUID) -> list[Obra]: ...
    def list_by_grupo(self, grupo_id: UUID) -> list[Obra]: ...
    def add(self, item: Obra) -> None: ...
    def save(self, item: Obra) -> None: ...
    def tiene_comprobantes_vivos(self, obra_id: UUID, empresa_id: UUID) -> bool: ...


class UsuarioRepository(Protocol):
    def get(self, id: UUID) -> Usuario | None: ...
    def get_by_email(self, email: str) -> Usuario | None: ...
    def list_by_grupo(self, grupo_id: UUID) -> list[Usuario]: ...
    def add(self, item: Usuario) -> None: ...
    def save(self, item: Usuario) -> None: ...


class ProveedorRepository(Protocol):
    def get(self, id: UUID) -> Proveedor | None: ...
    def list_by_grupo(self, grupo_id: UUID) -> list[Proveedor]: ...
    def get_by_cuit(self, cuit: str) -> Proveedor | None: ...
    def add(self, item: Proveedor) -> None: ...
    def save(self, item: Proveedor) -> None: ...


class RubroRepository(Protocol):
    def get(self, id: UUID) -> Rubro | None: ...
    def list_by_empresa(self, empresa_id: UUID) -> list[Rubro]: ...
    def add(self, item: Rubro) -> None: ...
    def save(self, item: Rubro) -> None: ...


class TipoPagoRepository(Protocol):
    def get(self, id: UUID) -> TipoPago | None: ...
    def list_by_empresa(self, empresa_id: UUID) -> list[TipoPago]: ...
    def add(self, item: TipoPago) -> None: ...
    def save(self, item: TipoPago) -> None: ...


class RefreshTokenRepository(Protocol):
    def add(self, item: RefreshToken) -> None: ...
    def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    def revoke(self, token_hash: str) -> None: ...


class GrupoReader(Protocol):
    def get_unico(self) -> tuple[UUID, str]: ...
    def ensure_seed_grupo(self, nombre: str, dueno: str) -> UUID: ...


class ComprobanteRepository(Protocol):
    def get(self, id: UUID) -> Comprobante | None: ...
    def add(self, item: Comprobante) -> None: ...
    def save(self, item: Comprobante) -> None: ...
    def get_by_clave_afip(
        self, cuit_emisor: str, tipo_afip: str, punto_venta: int, numero: int
    ) -> Comprobante | None: ...
    def listar(
        self,
        empresa_id: UUID | None = None,
        obra_id: UUID | None = None,
        estado_pago: str | None = None,
        desde: date | None = None,
        hasta: date | None = None,
        cliente_id: UUID | None = None,
        proveedor_id: UUID | None = None,
        clasificacion: str | None = None,
        rubro_id: UUID | None = None,
        tipo_pago_id: UUID | None = None,
        q: str | None = None,
        limit: int = 500,
        offset: int = 0,
    ) -> list[Comprobante]: ...
    def posible_duplicado_foto(
        self, sha256: str, proveedor_id: UUID | None, numero: int | None, fecha
    ) -> Comprobante | None: ...
    def tiene_vivos(self, obra_id: UUID, empresa_id: UUID) -> bool: ...
