from datetime import datetime
from typing import Protocol
from uuid import UUID


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenService(Protocol):
    def emit_access(self, user_id: UUID, rol: str) -> str: ...
    def emit_refresh(self) -> tuple[str, str, datetime]: ...
    def parse_access(self, token: str) -> tuple[UUID, str]: ...
    def hash_refresh(self, raw: str) -> str: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
